/*
 * All database access for the admin service catalog.
 *
 * Every write runs through supabaseAdmin, which uses the service
 * role. Migration 022 revoked INSERT, UPDATE and DELETE on
 * public.services from authenticated, so this module is the only
 * path by which a service row changes.
 */

import { supabaseAdmin } from "../../lib/supabase.js";
import {
  formatPriceDisplay,
  type ServiceBillingType,
  type ServiceCurrency,
  type ServiceRecurringInterval,
  type StructuredPricing,
} from "./admin-service.schema.js";

export const SERVICE_COLUMNS =
  [
    "id",
    "name",
    "description",
    "price_display",
    "is_active",
    "sort_order",
    "created_at",
    "updated_at",
    "billing_type",
    "recurring_interval",
    "price_cents",
    "currency",
    "stripe_product_id",
    "stripe_price_id",
    "stripe_payment_link_id",
    "stripe_payment_link_url",
  ].join(", ");

export type ServiceRow = {
  id: string;
  name: string;
  description: string | null;
  price_display: string | null;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
  billing_type:
    | ServiceBillingType
    | null;
  recurring_interval:
    | ServiceRecurringInterval
    | null;
  price_cents: number | null;
  currency: ServiceCurrency | null;
  stripe_product_id: string | null;
  stripe_price_id: string | null;
  stripe_payment_link_id:
    | string
    | null;
  stripe_payment_link_url:
    | string
    | null;
};

/*
 * Enumerated from the live schema, as PROJECT_LOCK Amendment 004
 * section 13.3 requires: the set checked in code is the set the
 * database actually carries, not an assumed set.
 *
 * Confirmed against pg_constraint while authoring and verifying
 * migration 022. The foreign keys referencing public.services are
 * exactly:
 *
 *   service_recommendations_service_id_fkey
 *     service_recommendations.service_id -> services.id
 *
 *   service_requests_service_id_fkey
 *     service_requests.service_id -> services.id
 *
 * Both are NO ACTION on delete and on update. Section 13.5
 * prohibits cascade or set-null here, so a referencing row always
 * blocks deletion rather than being rewritten.
 *
 * If a further referencing table is ever added, this constant
 * must be extended in the same change. See the deletion tests,
 * which assert a blocked delete performs no mutation at all.
 */
export const SERVICE_REFERENCING_TABLES =
  [
    "service_recommendations",
    "service_requests",
  ] as const;

export type ServiceReferencingTable =
  (typeof SERVICE_REFERENCING_TABLES)[number];

type RepositoryResult<T> =
  | {
      ok: true;
      value: T;
    }
  | {
      ok: false;
    };

const logDatabaseError = (
  operation: string,
  context: Record<string, unknown>,
  error: {
    code?: string | null;
    message?: string | null;
    details?: string | null;
    hint?: string | null;
  },
): void => {
  console.error(
    `Admin service ${operation} failed`,
    {
      ...context,
      code: error.code,
      message: error.message,
      details: error.details,
      hint: error.hint,
    },
  );
};

export const getServiceById = async (
  serviceId: string,
): Promise<
  RepositoryResult<ServiceRow | null>
> => {
  const { data, error } =
    await supabaseAdmin
      .from("services")
      .select(SERVICE_COLUMNS)
      .eq("id", serviceId)
      .maybeSingle();

  if (error) {
    logDatabaseError(
      "lookup",
      { serviceId },
      error,
    );

    return { ok: false };
  }

  return {
    ok: true,
    value:
      data as unknown as ServiceRow | null,
  };
};

/*
 * Inserted with an explicit id generated by the orchestrator.
 *
 * The identifier is recorded in the idempotency record before
 * this call, so a retry that arrives after a crash can find the
 * row it already created instead of inserting a second one. The
 * explicit id also means a concurrent duplicate collides on the
 * primary key rather than duplicating.
 *
 * The row is always created inactive and entirely unpriced, per
 * Amendment 004 sections 4.2 and 12.1.2.
 */
export const insertService = async ({
  serviceId,
  name,
  description,
  sortOrder,
}: {
  serviceId: string;
  name: string;
  description: string | null;
  sortOrder: number | null;
}): Promise<
  RepositoryResult<ServiceRow>
> => {
  const { data, error } =
    await supabaseAdmin
      .from("services")
      .insert({
        id: serviceId,
        name,
        description,
        ...(sortOrder === null
          ? {}
          : {
              sort_order: sortOrder,
            }),
        is_active: false,
      })
      .select(SERVICE_COLUMNS)
      .maybeSingle();

  if (error) {
    logDatabaseError(
      "insert",
      { serviceId },
      error,
    );

    return { ok: false };
  }

  if (!data) {
    console.error(
      "Admin service insert returned no row",
      { serviceId },
    );

    return { ok: false };
  }

  return {
    ok: true,
    value:
      data as unknown as ServiceRow,
  };
};

export const updateDescriptiveFields =
  async ({
    serviceId,
    name,
    description,
    sortOrder,
  }: {
    serviceId: string;
    name?: string;
    description?: string | null;
    sortOrder?: number;
  }): Promise<
    RepositoryResult<null>
  > => {
    const patch: Record<
      string,
      unknown
    > = {};

    if (name !== undefined) {
      patch.name = name;
    }

    if (description !== undefined) {
      patch.description = description;
    }

    if (sortOrder !== undefined) {
      patch.sort_order = sortOrder;
    }

    if (
      Object.keys(patch).length === 0
    ) {
      return {
        ok: true,
        value: null,
      };
    }

    const { error } =
      await supabaseAdmin
        .from("services")
        .update(patch)
        .eq("id", serviceId);

    if (error) {
      logDatabaseError(
        "descriptive update",
        { serviceId },
        error,
      );

      return { ok: false };
    }

    return {
      ok: true,
      value: null,
    };
  };

/*
 * Persisted on its own, immediately after the Product is created.
 *
 * The Product identifier is stable and pricing independent, and
 * migration 022 constrains it only by its own partial unique
 * index, so an early write cannot produce an incoherent row. It
 * guarantees a retry reuses the Product rather than creating a
 * second one, which section 8.1.1 forbids.
 */
export const persistProductId = async ({
  serviceId,
  stripeProductId,
}: {
  serviceId: string;
  stripeProductId: string;
}): Promise<
  RepositoryResult<null>
> => {
  const { error } =
    await supabaseAdmin
      .from("services")
      .update({
        stripe_product_id:
          stripeProductId,
      })
      .eq("id", serviceId);

  if (error) {
    logDatabaseError(
      "product id persistence",
      { serviceId, stripeProductId },
      error,
    );

    return { ok: false };
  }

  return { ok: true, value: null };
};

/*
 * The single atomic write.
 *
 * Pricing columns and the Price and Payment Link identifiers move
 * together in one statement. Migration 022 places no constraint
 * tying the Stripe identifiers to the pricing values, so a staged
 * write would be legal - which is precisely why it must not
 * happen. A row advertising one price while pointing at another
 * price's Payment Link is the worst outcome available here, and
 * only atomicity rules it out.
 */
export const persistPricingAndStripeIdentifiers =
  async ({
    serviceId,
    pricing,
    stripePriceId,
    stripePaymentLinkId,
    stripePaymentLinkUrl,
  }: {
    serviceId: string;
    pricing: StructuredPricing;
    stripePriceId: string;
    stripePaymentLinkId: string;
    stripePaymentLinkUrl: string;
  }): Promise<
    RepositoryResult<null>
  > => {
    const { error } =
      await supabaseAdmin
        .from("services")
        .update({
          billing_type:
            pricing.billingType,
          recurring_interval:
            pricing.recurringInterval,
          price_cents:
            pricing.priceCents,
          currency: pricing.currency,
          /*
           * Generated here, never accepted from a client
           * (section 6.2), and written in the same statement as
           * the pricing it describes so the two cannot diverge.
           */
          price_display:
            formatPriceDisplay(pricing),
          stripe_price_id:
            stripePriceId,
          stripe_payment_link_id:
            stripePaymentLinkId,
          stripe_payment_link_url:
            stripePaymentLinkUrl,
        })
        .eq("id", serviceId);

    if (error) {
      logDatabaseError(
        "pricing persistence",
        { serviceId },
        error,
      );

      return { ok: false };
    }

    return {
      ok: true,
      value: null,
    };
  };

/*
 * Clearing returns the service to fully unpriced.
 *
 * stripe_product_id is deliberately retained: one Product exists
 * per service for the life of that service (section 8.1.1), and
 * the Product survives a pricing removal.
 */
export const clearPricing = async (
  serviceId: string,
): Promise<
  RepositoryResult<null>
> => {
  const { error } =
    await supabaseAdmin
      .from("services")
      .update({
        billing_type: null,
        recurring_interval: null,
        price_cents: null,
        currency: null,
        /*
         * The generated display string describes structured
         * pricing that no longer exists, so it is cleared with
         * it rather than left behind as a stale claim.
         */
        price_display: null,
        stripe_price_id: null,
        stripe_payment_link_id: null,
        stripe_payment_link_url: null,
      })
      .eq("id", serviceId);

  if (error) {
    logDatabaseError(
      "pricing clear",
      { serviceId },
      error,
    );

    return { ok: false };
  }

  return { ok: true, value: null };
};

/*
 * Repairs a stale or missing display string on a service that
 * already carries structured pricing.
 *
 * Needed because rows priced before this formatter existed, or
 * left behind by an interrupted provisioning, would otherwise
 * keep advertising a value that no longer matches their pricing.
 */
export const persistPriceDisplay = async ({
  serviceId,
  priceDisplay,
}: {
  serviceId: string;
  priceDisplay: string;
}): Promise<
  RepositoryResult<null>
> => {
  const { error } =
    await supabaseAdmin
      .from("services")
      .update({
        price_display: priceDisplay,
      })
      .eq("id", serviceId);

  if (error) {
    logDatabaseError(
      "price display repair",
      { serviceId },
      error,
    );

    return { ok: false };
  }

  return { ok: true, value: null };
};

export const setActiveState = async ({
  serviceId,
  isActive,
}: {
  serviceId: string;
  isActive: boolean;
}): Promise<
  RepositoryResult<null>
> => {
  const { error } =
    await supabaseAdmin
      .from("services")
      .update({ is_active: isActive })
      .eq("id", serviceId);

  if (error) {
    logDatabaseError(
      "activation state update",
      { serviceId, isActive },
      error,
    );

    return { ok: false };
  }

  return { ok: true, value: null };
};

export const deleteService = async (
  serviceId: string,
): Promise<
  RepositoryResult<null>
> => {
  const { error } =
    await supabaseAdmin
      .from("services")
      .delete()
      .eq("id", serviceId);

  if (error) {
    logDatabaseError(
      "delete",
      { serviceId },
      error,
    );

    return { ok: false };
  }

  return { ok: true, value: null };
};

export type ServiceReferenceCounts = {
  references: Record<string, number>;
  total: number;
};

/*
 * Counts are taken per referencing table so a refusal can tell
 * the administrator exactly what is holding the service, which
 * section 13.4 requires in order to direct them to deactivate.
 */
export const countServiceReferences =
  async (
    serviceId: string,
  ): Promise<
    RepositoryResult<ServiceReferenceCounts>
  > => {
    const references: Record<
      string,
      number
    > = {};

    let total = 0;

    for (const table of SERVICE_REFERENCING_TABLES) {
      const { count, error } =
        await supabaseAdmin
          .from(table)
          .select("id", {
            count: "exact",
            head: true,
          })
          .eq(
            "service_id",
            serviceId,
          );

      if (error) {
        logDatabaseError(
          "reference count",
          { serviceId, table },
          error,
        );

        return { ok: false };
      }

      /*
       * A missing count is not zero references.
       *
       * Treating null, undefined or NaN as zero would let a
       * degraded count query authorise the deletion of a
       * referenced service, orphaning historical records that
       * section 13.5 requires be preserved. Anything that is not
       * a finite number fails closed.
       */
      if (
        typeof count !== "number" ||
        !Number.isFinite(count)
      ) {
        console.error(
          "Admin service reference count returned no usable value",
          { serviceId, table },
        );

        return { ok: false };
      }

      references[table] = count;
      total += count;
    }

    return {
      ok: true,
      value: { references, total },
    };
  };
